name: Deployment Pipeline

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: subdir/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
