name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Preivous Redundant builds
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{github.token}}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          command: npm run test:e2e
          start: npm run dev
          wait-on: http://localhost:5173
          browser: chrome
      - name: Deploy to Heroku
        if: ${{github.event_name=='push'}}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
